import type { Metadata } from "next";
import { sfPro } from "@/public/fonts/font.js";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${sfPro.className}`}>{children}</body>
    </html>
  );
}
